version: '3.1'
services:
  app:
    container_name: postgres-docker
    image: passcode
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - main_db
  postgresqldb:
    image: postgres
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres