version: '3'

services:
  postgres:
    image: 'postgres:16'
    container_name: 'postgres-docker'
    ports:
    - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=main_db'